version: "3"
services:
  api:
    build: .
    ports: ['8080:8080'] 
    volumes: 
      - .:/usr/src/app
    depends_on:
      - api_db
  api_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: api_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - api_db:/var/lib/mysql
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./seed.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - "33306:3306"

volumes:
  api_db: 